-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(*) as USERS FROM(SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, b.GENDER FROM ONLINE_SALE o
JOIN (SELECT * FROM USER_INFO 
WHERE GENDER IS NOT NULL) b
on b.USER_ID = o.USER_ID
GROUP BY YEAR, MONTH, o.USER_ID)a
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER

