-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, ROUND(a.DAILY_FEE * 30 * (100 - c.DISCOUNT_RATE) / 100, 0) as FEE FROM CAR_RENTAL_COMPANY_CAR a
JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE LIKE '30%' AND CAR_TYPE IN ('SUV', '세단'))c on a.CAR_TYPE = c.CAR_TYPE
WHERE (A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')))
HAVING FEE >= 500000 and FEE < 2000000
ORDER BY 3 desc, 2, 1 desc