SELECT YEAR, MONTH, COUNT(*) as PUCHASED_USERS,ROUND(COUNT(*)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) as PUCHASED_RATIO FROM (SELECT YEAR(sales_date) as YEAR, MONTH(sales_date) as MONTH, s1.USER_ID FROM ONLINE_SALE s1
JOIN (SELECT USER_ID FROM USER_INFO 
WHERE YEAR(JOINED) = '2021') s2 on s1.USER_ID = s2.USER_ID
GROUP BY s1.USER_ID, MONTH)a
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH