-- 코드를 입력하세요
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME FROM ANIMAL_INS i
JOIN 
(SELECT * FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME LIKE 'Neutered%' or SEX_UPON_OUTCOME LIKE 'Spayed%')o
on o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.SEX_UPON_INTAKE LIKE 'Intact%'