-- 코드를 입력하세요
WITH RECURSIVE EMPTY_TABLE as (
SELECT 0 as HOUR
UNION
SELECT HOUR + 1 FROM EMPTY_TABLE
WHERE HOUR < 23
)

SELECT e.HOUR, IFNULL(a.COUNT, '0') as COUNT FROM EMPTY_TABLE e
LEFT JOIN (SELECT HOUR(DATETIME) as HOUR, COUNT(*) as COUNT FROM ANIMAL_OUTS GROUP BY HOUR) a 
on a.HOUR = e.HOUR