SELECT ct.CATEGORY, ct.PRICE as MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT ct
JOIN (SELECT CATEGORY, MAX(PRICE) as PRICE FROM FOOD_PRODUCT
GROUP BY CATEGORY) cr on ct.CATEGORY = cr.CATEGORY and ct.PRICE = cr.PRICE
WHERE ct.CATEGORY IN ('국', '과자', '김치', '식용유')
ORDER BY MAX_PRICE desc