-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE FROM REST_REVIEW rr
JOIN (SELECT MEMBER_ID, COUNT(MEMBER_ID) as COUNT FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT desc
LIMIT 1)fr on rr.MEMBER_ID = fr.MEMBER_ID
JOIN (SELECT * FROM MEMBER_PROFILE)mp on mp.MEMBER_ID = rr.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT