-- 코드를 입력하세요
SELECT APNT_NO, p.PT_NAME, p.PT_NO, MCDP_CD, DR_NAME, APNT_YMD FROM APPOINTMENT a
JOIN (SELECT PT_NO, PT_NAME FROM PATIENT)p on p.PT_NO = a.PT_NO
JOIN (SELECT DR_ID, DR_NAME FROM DOCTOR)d on d.DR_ID = a.MDDR_ID
WHERE APNT_CNCL_YN = 'N' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND MCDP_CD = 'CS'
ORDER BY APNT_YMD